CREATE TABLE IF NOT EXISTS people (
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	iin VARCHAR(12) PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	phone VARCHAR(15) NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_people_iin ON people (iin);